# Generated by Django 4.2.2 on 2023-10-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_totpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_users',
            field=models.IntegerField(default=1),
        ),
    ]
