# Generated by Django 4.2.2 on 2023-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_create_date_organization_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='abuse_flag',
            field=models.BooleanField(default=False),
        ),
    ]
