# Generated by Django 4.2.2 on 2023-12-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_abuse_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jobtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role_readonly',
            field=models.BooleanField(default=False),
        ),
    ]
