# Generated by Django 4.2.1 on 2023-05-30 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_description', models.TextField()),
                ('hazardous_events', models.TextField()),
                ('causes', models.TextField()),
                ('consequences', models.TextField()),
                ('safeguards', models.TextField()),
                ('layers_of_protection', models.TextField()),
                ('risk_ranking', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('risk_reduction_measures', models.TextField()),
                ('risk_residual_level', models.CharField(max_length=100)),
                ('acceptability_criteria', models.CharField(max_length=100)),
                ('threats', models.TextField()),
                ('vulnerabilities', models.TextField()),
                ('impact_analysis', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('likelihood_assessment', models.TextField()),
                ('risk_evaluation', models.TextField()),
                ('risk_mitigation', models.TextField()),
                ('status', models.CharField(choices=[('D', 'In Progress'), ('P', 'Under Review')], default='D', max_length=1)),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('enddate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('riskauthor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ra_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-startdate'],
                'indexes': [models.Index(fields=['-startdate'], name='OTRisk_post_startda_87a366_idx')],
            },
        ),
    ]
