# Generated by Django 4.2.1 on 2023-05-31 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='OTRisk.post')),
            ],
        ),
    ]
