# Generated by Django 4.2.2 on 2023-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0002_tblcyberphascenario_sle_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworksheetscenario',
            name='risk_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='risk_register',
            field=models.BooleanField(default=False),
        ),
    ]
