# Generated by Django 4.2.2 on 2023-09-13 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
        migrations.CreateModel(
            name='tblCyberPHAScenario',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CyberPHA', models.IntegerField()),
                ('Scenario', models.CharField(max_length=255)),
                ('ThreatClass', models.CharField(max_length=100)),
                ('ThreatAgent', models.CharField(max_length=100)),
                ('ThreatAction', models.CharField(max_length=100)),
                ('Countermeasures', models.CharField(max_length=500)),
                ('RiskCategory', models.CharField(max_length=100)),
                ('Consequence', models.CharField(max_length=1000)),
                ('impactSafety', models.IntegerField()),
                ('impactDanger', models.IntegerField()),
                ('impactProduction', models.IntegerField()),
                ('impactFinance', models.IntegerField()),
                ('impactReputation', models.IntegerField()),
                ('impactEnvironment', models.IntegerField()),
                ('impactRegulation', models.IntegerField()),
                ('impactData', models.IntegerField()),
                ('impactSupply', models.IntegerField()),
                ('UEL', models.IntegerField()),
                ('RRU', models.IntegerField()),
                ('SM', models.IntegerField()),
                ('MEL', models.IntegerField()),
                ('RRM', models.IntegerField()),
                ('SA', models.IntegerField()),
                ('MELA', models.IntegerField()),
                ('RRa', models.TextField()),
                ('sl', models.IntegerField()),
                ('recommendations', models.CharField(max_length=1000)),
                ('Deleted', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('aro', models.IntegerField()),
                ('sle', models.IntegerField()),
                ('ale', models.IntegerField()),
                ('countermeasureCosts', models.IntegerField()),
                ('control_recommendations', models.TextField()),
                ('justifySafety', models.TextField()),
                ('justifyLife', models.TextField()),
                ('justifyProduction', models.TextField()),
                ('justifyFinancial', models.TextField()),
                ('justifyReputation', models.TextField()),
                ('justifyEnvironment', models.TextField()),
                ('justifyRegulation', models.TextField()),
                ('justifyData', models.TextField()),
                ('justifySupply', models.TextField()),
                ('standards', models.TextField()),
                ('outage', models.TextField()),
                ('outageDuration', models.IntegerField()),
                ('outageCost', models.IntegerField()),
                ('probability', models.TextField()),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblCyberPHAScenario',
            },
        )


