# Generated by Django 4.2.2 on 2023-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0005_alter_tblcyberphascenario_cyberpha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='annual_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='cyber_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='shift_model',
            field=models.CharField(choices=[('Single Shift Model', 'Single Shift Model'), ('Double Shift Model', 'Double Shift Model'), ('Three-Shift (24/7) Model', 'Three-Shift (24/7) Model'), ('Rotating Shift Model', 'Rotating Shift Model'), ('Fixed Shift Model', 'Fixed Shift Model'), ('Split Shift Model', 'Split Shift Model'), ('On-Call or Flex Shift Model', 'On-Call or Flex Shift Model'), ('Compressed Workweek Model', 'Compressed Workweek Model'), ('Part-Time or Seasonal Model', 'Part-Time or Seasonal Model'), ('Hybrid Shift Models', 'Hybrid Shift Models')], default='Hybrid Shift Models', max_length=50),
            preserve_default=False,
        ),
    ]
