# Generated by Django 4.2.2 on 2023-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0006_tblcyberphaheader_annual_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='safety_hazard',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='sis_compromise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='sis_outage',
            field=models.BooleanField(default=False),
        ),
    ]
