# Generated by Django 4.2.2 on 2023-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0007_tblcyberphascenario_safety_hazard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='risk_owner',
            field=models.TextField(default='Unassigned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='risk_priority',
            field=models.TextField(default='Unassigned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='risk_response',
            field=models.CharField(choices=[('Manage', 'Manage'), ('Mitigate', 'Mitigate'), ('Transfer', 'Transfer'), ('Accept', 'Accept')], default='Manage', max_length=50),
            preserve_default=False,
        ),
    ]
