# Generated by Django 4.2.2 on 2023-10-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0008_tblcyberphascenario_risk_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='risk_close_date',
            field=models.DateField(default='2099-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='risk_open_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='risk_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblcyberphascenario',
            name='risk_priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=50),
        ),
    ]
