# Generated by Django 4.2.2 on 2023-10-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_totpdevice'),
        ('OTRisk', '0010_cyberphascenario_snapshot'),
    ]

    operations = [

        migrations.AddField(
            model_name='tblcyberphascenario',
            name='uel_exposure',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='uel_threat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='uel_vuln',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),

    ]
