# Generated by Django 4.2.2 on 2023-10-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_totpdevice'),
        ('OTRisk', '0011_cyberphascenario_snapshot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='uel_exposure',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='uel_threat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='uel_vuln',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
