# Generated by Django 4.2.2 on 2023-10-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0015_alter_cyberphascenario_snapshot_cyberpha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='control_effectiveness',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='control_effectiveness',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
