# Generated by Django 4.2.2 on 2023-10-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0017_tblcyberphaheader_compliancesummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='pha_score',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
