# Generated by Django 4.2.2 on 2023-10-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0018_tblcyberphaheader_pha_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='likelihood',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
