# Generated by Django 4.2.2 on 2023-10-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0019_tblcyberphascenario_likelihood'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='likelihood',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
