# Generated by Django 4.2.2 on 2023-10-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0020_cyberphascenario_snapshot_likelihood'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworksheetscenario',
            name='impact',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Damage to Property', 'Damage to Property'), ('Denial of Control', 'Denial of Control'), ('Denial of View', 'Denial of View'), ('Loss of Availability', 'Loss of Availability'), ('Loss of Control', 'Loss of Control'), ('Loss of Productivity and Revenue', 'Loss of Productivity and Revenue'), ('Loss of Protection', 'Loss of Protection'), ('Loss of Safety', 'Loss of Safety'), ('Loss of View', 'Loss of View'), ('Manipulation of Control', 'Manipulation of Control'), ('Manipulation of View', 'Manipulation of View'), ('Theft of Operational Information', 'Theft of Operational Information')], default='N/A', max_length=30),
        ),
    ]
