# Generated by Django 4.2.2 on 2023-10-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0023_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblscenarios',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OTRisk.tblindustry'),
        ),
    ]
