# Generated by Django 4.2.2 on 2023-10-24 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0025_vulnerability_analysis_cve_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworksheetscenario',
            name='residual_risk',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RawControlList',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('control', models.TextField()),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scenarioID', models.ForeignKey(db_column='scenarioID', on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='OTRisk.raworksheetscenario')),
            ],
            options={
                'verbose_name': 'Control List',
                'verbose_name_plural': 'Control Lists',
                'db_table': 'tblRawControlList',
            },
        ),
    ]
