# Generated by Django 4.2.2 on 2023-10-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0028_cyberphascenario_snapshot_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cyberpha_safety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('cyberphaID', models.ForeignKey(db_column='cyberphaID', on_delete=django.db.models.deletion.CASCADE, to='OTRisk.tblcyberphaheader')),
            ],
            options={
                'db_table': 'cyberpha_safety',
            },
        ),
        migrations.CreateModel(
            name='cyberpha_physicalsecurity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('cyberphaID', models.ForeignKey(db_column='cyberphaID', on_delete=django.db.models.deletion.CASCADE, to='OTRisk.tblcyberphaheader')),
            ],
            options={
                'db_table': 'cyberpha_physicalsecurity',
            },
        ),
        migrations.CreateModel(
            name='cyberpha_ot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('cyberphaID', models.ForeignKey(db_column='cyberphaID', on_delete=django.db.models.deletion.CASCADE, to='OTRisk.tblcyberphaheader')),
            ],
            options={
                'db_table': 'cyberpha_ot',
            },
        ),
        migrations.CreateModel(
            name='cyberpha_compliance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('cyberphaID', models.ForeignKey(db_column='cyberphaID', on_delete=django.db.models.deletion.CASCADE, to='OTRisk.tblcyberphaheader')),
            ],
            options={
                'db_table': 'cyberpha_compliance',
            },
        ),
        migrations.CreateModel(
            name='cyberpha_chemical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('cyberphaID', models.ForeignKey(db_column='cyberphaID', on_delete=django.db.models.deletion.CASCADE, to='OTRisk.tblcyberphaheader')),
            ],
            options={
                'db_table': 'cyberpha_chemical',
            },
        ),
    ]
