# Generated by Django 4.2.2 on 2023-11-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0031_cyberphascenario_snapshot_sl_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblconsequence',
            options={'managed': True},
        ),
    ]
