# Generated by Django 4.2.2 on 2023-11-05 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_max_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OTRisk', '0033_tblconsequence_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='raworksheet',
            name='StatusFlag',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=6),
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(to='OTRisk.assessmentanswer')),
                ('cyber_pha_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OTRisk.tblcyberphaheader')),
                ('cyber_pha_scenario', models.ManyToManyField(blank=True, to='OTRisk.tblcyberphascenario')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTRisk.assessmentframework')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('guidance', models.TextField(blank=True, null=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTRisk.assessmentframework')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTRisk.assessmentquestion'),
        ),
    ]
