# Generated by Django 4.2.2 on 2023-11-05 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0034_assessmentanswer_assessmentframework_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentanswer',
            name='text',
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='effectiveness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='response',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='weighting',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='section_reference',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
