# Generated by Django 4.2.2 on 2023-11-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_max_users'),
        ('OTRisk', '0035_remove_assessmentanswer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDefaults',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='defaults', serialize=False, to='accounts.organization')),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('annual_revenue', models.IntegerField(blank=True, null=True)),
                ('cyber_insurance', models.IntegerField(blank=True, null=True)),
                ('insurance_deductible', models.IntegerField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OTRisk.tblindustry')),
            ],
        ),
    ]
