# Generated by Django 4.2.2 on 2023-11-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0036_organizationdefaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdefaults',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('ar', 'Arabic'), ('ja', 'Japanese'), ('zh', 'Mandarin')], max_length=30, null=True),
        ),
    ]
