# Generated by Django 4.2.2 on 2023-11-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0039_raworksheet_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_contaminants',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Chemical', 'Chemical'), ('Biological', 'Biological'), ('Radiological', 'Radiological'), ('Physical', 'Physical')], default='N/A', max_length=12),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_contamination',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Localized', 'Localized'), ('Wide Area', 'Wide Area')], default='N/A', max_length=12),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_data_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_data_finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_data_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_data_pii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_ecosystem',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Aquatic', 'Aquatic'), ('Terrestrial', 'Terrestrial'), ('Urban', 'Urban'), ('Agriculture', 'Agriculture')], default='N/A', max_length=12),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_life_scope',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Facility', 'Facility'), ('External', 'External'), ('Both', 'Both')], default='N/A', max_length=12),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_resident',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Harmless', 'Harmless'), ('Harmful', 'Harmful'), ('Deadly', 'Deadly')], default='N/A', max_length=12),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_safety_hazard',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Chemical', 'Chemical'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Radiation', 'Radiation')], default='N/A', max_length=12),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_sis_compromise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_sis_outage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_supply_inbound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_supply_outbound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_supply_prodimpact',
            field=models.CharField(default='Low', max_length=6),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_supply_security',
            field=models.CharField(default='Low', max_length=6),
        ),
        migrations.AddField(
            model_name='raworksheetscenario',
            name='bia_wildlife',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Harmless', 'Harmless'), ('Harmful', 'Harmful'), ('Deadly', 'Deadly')], default='N/A', max_length=12),
        ),
    ]
