# Generated by Django 4.2.2 on 2023-11-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0040_raworksheetscenario_bia_contaminants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='dangerScope',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
