# Generated by Django 4.2.2 on 2023-11-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0041_tblcyberphascenario_dangerscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
