# Generated by Django 4.2.2 on 2023-11-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0042_assessmentquestion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentanswer',
            name='response',
            field=models.BooleanField(null=True),
        ),
    ]
