# Generated by Django 4.2.2 on 2023-11-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0044_selfassessment_name_selfassessment_score_effective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='assessment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
