# Generated by Django 4.2.2 on 2023-11-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0045_tblcyberphaheader_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentframework',
            name='owner_organization',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
