# Generated by Django 4.2.2 on 2023-11-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0046_assessmentframework_owner_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='ai_bia_score',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
