# Generated by Django 4.2.2 on 2023-11-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0047_tblcyberphascenario_ai_bia_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='ale_high',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='ale_low',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='ale_median',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='ale_high',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='ale_low',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='ale_median',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
