# Generated by Django 4.2.2 on 2023-11-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0048_cyberphascenario_snapshot_ale_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='dangerScope',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
