# Generated by Django 4.2.2 on 2023-11-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0049_cyberphascenario_snapshot_dangerscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='env_contaminant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='env_contamination',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='env_ecosystem',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='env_population',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='env_wildlife',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='env_contaminant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='env_contamination',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='env_ecosystem',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='env_population',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='env_wildlife',
            field=models.TextField(null=True),
        ),
    ]
