# Generated by Django 4.2.2 on 2023-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0050_cyberphascenario_snapshot_env_contaminant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdefaults',
            name='impact_weight_danger',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationdefaults',
            name='impact_weight_data',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationdefaults',
            name='impact_weight_environment',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationdefaults',
            name='impact_weight_finance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationdefaults',
            name='impact_weight_production',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationdefaults',
            name='impact_weight_regulation',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationdefaults',
            name='impact_weight_reputation',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationdefaults',
            name='impact_weight_safety',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationdefaults',
            name='impact_weight_supply',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='bia_scenarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='risk_scenarios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
