# Generated by Django 4.2.2 on 2023-11-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0052_alter_organizationdefaults_impact_weight_danger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitycontrols',
            old_name='ControlTypeDescription',
            new_name='ControlDescription',
        ),
        migrations.AddField(
            model_name='securitycontrols',
            name='framework',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='securitycontrols',
            name='reference',
            field=models.TextField(null=True),
        ),
    ]
