# Generated by Django 4.2.2 on 2023-12-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0055_tblcyberphascenario_exposed_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='weak_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
