# Generated by Django 4.2.2 on 2023-12-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0056_tblcyberphascenario_weak_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='scenario_compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_issue', models.CharField(max_length=200)),
                ('regulation', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTRisk.tblcyberphascenario')),
            ],
        ),
    ]
