# Generated by Django 4.2.2 on 2023-12-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0057_scenario_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='exposed_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='weak_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
