# Generated by Django 4.2.2 on 2023-12-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0059_raworksheetscenario_exposed_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioConsequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequence_text', models.CharField(max_length=1000)),
                ('is_validated', models.BooleanField(default=False)),
                ('scenario', models.ForeignKey(db_column='Scenario', on_delete=django.db.models.deletion.CASCADE, to='OTRisk.tblcyberphascenario')),
            ],
            options={
                'db_table': 'scenario_consequences',
            },
        ),
    ]
