# Generated by Django 4.2.2 on 2023-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0061_tblcyberphaheader_insightsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='compliance_map',
            field=models.TextField(default='No Compliance Map Saved', null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='compliance_map',
            field=models.TextField(default='No Compliance Map Saved', null=True),
        ),
    ]
