# Generated by Django 4.2.2 on 2023-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0062_cyberphascenario_snapshot_compliance_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='attack_tree_text',
            field=models.TextField(null=True),
        ),
    ]
