# Generated by Django 4.2.2 on 2023-12-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0063_tblcyberphascenario_attack_tree_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='attack_tree_text',
            field=models.TextField(null=True),
        ),
    ]
