# Generated by Django 4.2.2 on 2023-12-22 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OTRisk', '0066_remove_auditlog_userid_auditlog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberPHAModerators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pha_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='OTRisk.tblcyberphaheader')),
            ],
            options={
                'db_table': 'cyberpha_moderators',
                'unique_together': {('pha_header', 'moderator')},
            },
        ),
    ]
