# Generated by Django 4.2.2 on 2023-12-22 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OTRisk', '0067_cyberphamoderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='scenario_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Final', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblcyberphascenario',
            name='risk_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=6),
        ),
        migrations.CreateModel(
            name='ScenarioModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impactSafety', models.IntegerField()),
                ('impactDanger', models.IntegerField()),
                ('impactProduction', models.IntegerField()),
                ('impactFinance', models.IntegerField()),
                ('impactReputation', models.IntegerField()),
                ('impactEnvironment', models.IntegerField()),
                ('impactRegulation', models.IntegerField()),
                ('impactData', models.IntegerField()),
                ('impactSupply', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTRisk.tblcyberphascenario')),
            ],
            options={
                'unique_together': {('scenario', 'moderator')},
            },
        ),
    ]
