# Generated by Django 4.2.2 on 2023-12-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0068_tblcyberphascenario_scenario_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcyberphascenario',
            name='scenario_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final'), ('Started', 'Started')], max_length=7),
        ),
    ]
