# Generated by Django 4.2.2 on 2023-12-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0069_alter_tblcyberphascenario_scenario_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomoderation',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
