# Generated by Django 4.2.2 on 2023-12-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0070_scenariomoderation_target_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariomoderation',
            name='target_date',
        ),
        migrations.AddField(
            model_name='cyberphamoderators',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
