# Generated by Django 4.2.2 on 2023-12-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0071_remove_scenariomoderation_target_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Started', 'Started'), ('In Progress', 'In Progress'), ('Waiting for Moderation', 'Waiting for Moderation'), ('Complete', 'Complete')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cyber_pha_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_statuses', to='OTRisk.tblcyberphaheader')),
            ],
        ),
    ]
