# Generated by Django 4.2.2 on 2023-12-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0073_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworksheetscenario',
            name='raw_consequences',
            field=models.TextField(null=True),
        ),
    ]
