# Generated by Django 4.2.2 on 2024-01-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0076_scenariobuilder'),
    ]

    operations = [
        migrations.CreateModel(
            name='attack_effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='attack_impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_impact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='attack_motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_motivation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='attack_motive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_motive', models.TextField()),
            ],
        ),
    ]
