# Generated by Django 4.2.2 on 2024-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0080_raworksheetscenario_scenario_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworksheetscenario',
            name='attack_tree',
            field=models.TextField(null=True),
        ),
    ]
