# Generated by Django 4.2.2 on 2024-02-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0082_qraw_safeguard'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworksheetscenario',
            name='scenario_12month_costs',
            field=models.TextField(null=True),
        ),
    ]
