# Generated by Django 4.2.2 on 2024-02-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0083_raworksheetscenario_scenario_12month_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='raworksheetscenario',
            name='executive_summary',
            field=models.TextField(null=True),
        ),
    ]
