# Generated by Django 4.2.2 on 2024-02-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0084_raworksheetscenario_executive_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHA_Safeguard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safeguard_description', models.TextField(max_length=255)),
                ('safeguard_type', models.CharField(max_length=100)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safeguards', to='OTRisk.tblcyberphascenario')),
            ],
            options={
                'db_table': 'tblPHASafeguard',
            },
        ),
    ]
