# Generated by Django 4.2.2 on 2024-02-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0086_scenariobuilder_cost_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberSecurityInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('People', 'People')], max_length=50)),
                ('vendor_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('cyber_pha_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='OTRisk.tblcyberphaheader')),
            ],
            options={
                'db_table': 'tblCyberSecurityInvestment',
            },
        ),
    ]
