# Generated by Django 4.2.2 on 2024-02-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0088_scenariobuilder_investment_projection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariobuilder',
            name='investment_projection',
        ),
    ]
