# Generated by Django 5.0.2 on 2024-02-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0089_remove_scenariobuilder_investment_projection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomScenario',
        ),
    ]
