# Generated by Django 5.0.2 on 2024-02-15 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0091_scenariobuilder_analysisresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('prompt', models.TextField()),
                ('model_used', models.CharField(max_length=30)),
                ('temperature', models.FloatField()),
                ('tokens_used_query', models.IntegerField()),
                ('tokens_used_response', models.IntegerField()),
                ('total_tokens_used', models.IntegerField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
