# Generated by Django 5.0.2 on 2024-02-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0092_openaiapilog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcyberphascenario',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
