# Generated by Django 5.0.2 on 2024-02-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0093_alter_tblcyberphascenario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='executive_summary',
            field=models.TextField(null=True),
        ),
    ]
