# Generated by Django 5.0.2 on 2024-02-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0094_tblcyberphascenario_executive_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphascenario',
            name='cost_projection',
            field=models.TextField(null=True),
        ),
    ]
