# Generated by Django 5.0.2 on 2024-02-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0095_tblcyberphascenario_cost_projection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='cost_projection',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cyberphascenario_snapshot',
            name='executive_summary',
            field=models.TextField(null=True),
        ),
    ]
