# Generated by Django 5.0.2 on 2024-02-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0096_cyberphascenario_snapshot_cost_projection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tblScenarioRecommendations',
        ),
    ]
