# Generated by Django 5.0.2 on 2024-02-19 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0098_userscenariohash_delete_tbldeviations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscenariohash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
