# Generated by Django 5.0.2 on 2024-02-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0099_userscenariohash_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='facilityAQI',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='facilityCity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='facilityCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='facilityLat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='facilityLong',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tblcyberphaheader',
            name='facilityState',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
