# Generated by Django 5.0.2 on 2024-02-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0100_tblcyberphaheader_facilityaqi_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raworksheetscenario',
            unique_together={('RAWorksheetID', 'ScenarioDescription')},
        ),
    ]
