# Generated by Django 5.0.2 on 2024-02-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTRisk', '0101_alter_raworksheetscenario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcyberphascenario',
            name='recommendations',
            field=models.TextField(null=True),
        ),
    ]
